# Site settings
title: "Le Trung Kien | Embedded Systems"
subtitle: "Linux Embedded Software Developer"
description: "Specializing in Linux kernel development, embedded systems, real-time applications, and IoT solutions. Sharing insights on system programming, driver development, and embedded Linux."
baseurl: ""
url: "https://yourdomain.com"

# Author settings
author:
  name: "Kien LT"
  title: "Linux Embedded Software Developer"
  bio: "Passionate Linux embedded developer with expertise in kernel development, device drivers, real-time systems, and IoT solutions. I specialize in low-level programming, system optimization, and building robust embedded applications."
  avatar: "/assets/img/avatar.jpg"
  email: "your-email@example.com"
  github: "your-github"
  linkedin: "your-linkedin"
  twitter: "your-twitter"
  specialties:
    - "Linux Kernel Development"
    - "Device Driver Programming"
    - "Real-time Systems"
    - "IoT & Embedded Solutions"
    - "System Programming"
    - "Hardware Integration"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
