# Site settings
title: "Viet-Anh on Software"
subtitle: "AI & Software Engineering"
description: "Welcome to my corner of the internet! I'm a passionate developer sharing insights on AI, Deep Learning, Software Engineering, and the journey of building meaningful technology."
baseurl: ""
url: "https://yourdomain.com"

# Author settings
author:
  name: "Viet-Anh"
  title: "Software Engineer"
  bio: "Welcome to my corner of the internet! I'm a passionate developer sharing insights on AI, Deep Learning, Software Engineering, and the journey of building meaningful technology. Join me as I explore the intersection of code and creativity."
  avatar: "/assets/img/avatar.jpg"
  email: "your-email@example.com"
  github: "your-github"
  linkedin: "your-linkedin"
  twitter: "your-twitter"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
